#!/bin/bash

TPUT_COLS=$(tput cols)
TPUT_LINES=$(tput lines)

print_coors () {
    local IFS=","
    local COORS=("${@}")

    for i in "${COORS[@]}"; do
        set $i
        echo -en "\033[$1;$2f$3"
    done
}

declare -a COORS=()
declare -a PID_LIST=()

for x in $(seq 1 $TPUT_COLS); do
    TMP=""

    if [ $(($x%2)) -eq 0 ]; then
        for y in $(seq 1 $TPUT_LINES); do
            if [ $(($y%2)) -eq 0 ]; then
                TMP+="\033[0;31m█"
            else
                TMP+="\033[0;32m█"
            fi
        done
    else
        for y in $(seq 1 $TPUT_LINES); do
            if [ $(($y%2)) -eq 0 ]; then
                TMP+="\033[0;32m█"
            else
                TMP+="\033[0;31m█"
            fi
        done
    fi

    COORS+=("$x,1,$TMP")
done

# time {
#     print_coors "${COORS[@]}"
# }

time {
    declare -a TMP=()

    for i in "${COORS[@]}"; do
        TMP+=($i)

        if [ "${#TMP[@]}" -eq $TPUT_LINES ]; then
            print_coors "${TMP[@]}"  &
            PID_LIST+=($!)
            TMP=()
        fi
    done

    if [ "${#TMP[@]}" -gt "0" ]; then
        print_coors "${TMP[@]}"  &
        PID_LIST+=($!)
        TMP=()
    fi

    for pid in "${PID_LIST[@]}"; do
        wait $pid
    done
}
