#!/bin/bash


                      ####                        ##                    
                    ##  ##                       ##                    
                   ##                           ##                    
                  ####  ## ###    ###    ###   ##     ## ###    ###
                 ##    #### ##  ## ##  ## ##  ####   #### ##  ## ##
                ##    ##       #####   ##    ## ##  ##       ##
               ##    ##       ##       ##   ## ##  ##       ##
         ##   ##    ##       ## ##  ## ##  ## ##  ##       ## ##
        ##   ##    ##        ###    ###   ## ##  ##        ###


#
# This is my freshrc file! Fresh helps manage my dotfiles in a pretty organised
# way, and also handles some lightweight bootstrapping on clean systems.
#

source ${FRESH_LOCAL}/shell/misc/command_exists
source ${FRESH_LOCAL}/shell/misc/fatal_error

# Ensure that the required commands are available
for cmd in "git"; do
  if ! command_exists ${cmd}; then
    fatal_error "${cmd} is not available in your path"
  fi
done

# Ensure that the local git configuration is setup correctly
for key in "name" "email"; do
  if [ -z "$(git config user.${key})" ]; then
    read -p "Enter ${key} for Git: " input
    git config -f ~/.gitconfig.local user.${key} "${input}"
  fi
done

fresh freshshell/fresh bin/fresh --bin

# Git
fresh git/gitconfig --file
fresh git/gitignore --file
fresh git/git-templates --file=~/.git-templates/

# Shell
fresh shell/bash/bash_profile --file

# Vim
fresh junegunn/vim-plug plug.vim --file=~/.vim/autoload/plug.vim

fresh editor/vim/vimrc    --file
fresh editor/vim/minisnip --file=~/.vim/minisnip/

# i3
fresh i3 --file=~/.config/i3/

