#!/bin/bash

for cmd in "git"; do
  if ! [ -x "$(command -v ${cmd})" ]; then
    echo "Error: ${cmd} is not available in your path"
    exit 1
  fi
done

# Ensure that the local git configuration is setup correctly
for key in "name" "email"; do
  if [ -z $(git config user.${key}) ]; then
    read -p "Enter ${key} for Git: " input
    git config -f ~/.gitconfig.local user.${key} "${input}"
  fi
done

fresh freshshell/fresh bin/fresh --bin

fresh git/gitconfig --file
fresh git/gitignore --file
fresh git/git-templates --file=~/.git-templates/
fresh shell/bash/bash_profile --file

# Vim
fresh junegunn/vim-plug plug.vim --file=~/.vim/autoload/plug.vim

fresh editor/vim/vimrc --file
fresh editor/vim/minisnip --file=~/.vim/minisnip/
