#!/bin/bash


                      ####                        ##                    
                    ##  ##                       ##                    
                   ##                           ##                    
                  ####  ## ###    ###    ###   ##     ## ###    ###
                 ##    #### ##  ## ##  ## ##  ####   #### ##  ## ##
                ##    ##       #####   ##    ## ##  ##       ##
               ##    ##       ##       ##   ## ##  ##       ##
         ##   ##    ##       ## ##  ## ##  ## ##  ##       ## ##
        ##   ##    ##        ###    ###   ## ##  ##        ###


#
# This is my freshrc file! Fresh helps manage my dotfiles in a pretty organised
# way, and also handles some lightweight bootstrapping on clean systems.
#

source ${FRESH_LOCAL}/bash/methods/command_exists
source ${FRESH_LOCAL}/bash/methods/fatal_error
source ${FRESH_LOCAL}/bash/methods/system_info

# Ensure that the required commands are available
for cmd in "git"; do
  if ! command_exists ${cmd}; then
    fatal_error "${cmd} is not available in your path"
  fi
done

# Ensure that the local git configuration is setup correctly
for key in "name" "email"; do
  if [ -z "$(git config user.${key})" ]; then
    read -p "Enter ${key} for Git: " input
    git config -f ~/.gitconfig.local user.${key} "${input}"
  fi
done

fresh freshshell/fresh bin/fresh --bin

# Git
fresh git/gitconfig     --file
fresh git/gitignore     --file
fresh git/git-templates --file=~/.git-templates/

# Bash
fresh bash/bashrc	--file
fresh bash/bash_profile --file

fresh iainreid820/banner-cli banner --bin=~/bin/banner
fresh iainreid820/prettyname-cli prettyname --bin=~/bin/prettyname

# Tmux
fresh tmux/tmux.conf --file

# Vim
fresh junegunn/vim-plug plug.vim --file=~/.vim/autoload/plug.vim

fresh vim/vimrc    --file=~/.vim/vimrc
fresh vim/ftdetect --file=~/.vim/ftdetect/
fresh vim/ftplugin --file=~/.vim/ftplugin/
fresh vim/minisnip --file=~/.vim/minisnip/

if system_info.is_osx; then
  if ! command_exists "brew"; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  fresh fwartner/mac-cleanup cleanup.sh --bin=~/bin/cleanup
fi


