#!/bin/bash

sandbox_init_fresh () {
  source ~/.fresh/build/shell.sh
}

sandbox_init_nvm () {
  export NVM_DIR="$HOME/.nvm"
  
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

sandbox_hook nvm node
sandbox_hook nvm npm

