" vi:syntax=vim

set laststatus=2
set backspace=indent,eol,start
set background=dark

" Open split panes in a more natural way
set splitbelow
set splitright

" Turn on syntax highlighting
syntax on

highlight VertSplit cterm=NONE

set fillchars+=vert:\│

" Statusline
set statusline=\ %f%=%y\ %p%%\ %c:%l\

" Simplify tab control
map <leader>t :tabnew <Enter>
map <leader>w :close <Enter>

map <leader>1 1gt
map <leader>2 2gt
map <leader>3 3gt
map <leader>4 4gt
map <leader>5 5gt
map <leader>6 6gt
map <leader>7 7gt
map <leader>8 8gt
map <leader>9 9gt

if has("mouse")
  set mouse=a
endif

" Simplify split pane navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Netrw setup
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

let g:sessiondir = $XDG_STATE_HOME . "/vim/session"

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, "p", 0700)
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, "p", 0700)
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   "p", 0700)

if (filewritable(g:sessiondir) != 2)
  exe "silent !mkdir -p " g:sessiondir
  redraw!
endif


" Set to ensure disk write for use with hot reloading
set nobackup nowritebackup

if executable("gtm")
  packadd! git-time-metric
endif

" Starts a new session
function StartSession()
  let b:sessionfile = g:sessiondir . getcwd() . ".vim"

  if (filereadable(b:sessionfile))
    echo "Session already exists"
  else
    exe "mksession! " . b:sessionfile
    echo "Session started"
  endif
endfunction

" Loads a session if it exists
function LoadSession()
  let b:sessionfile = g:sessiondir . getcwd() . ".vim"

  if (filereadable(b:sessionfile))
    exe "source " . b:sessionfile
    echo "Session loaded"
  else
    echo "Session doesn't exist"
  endif
endfunction

" Saves a session if it exists
function SaveSession()
  let b:sessionfile = g:sessiondir . getcwd() . ".vim"

  if (filereadable(b:sessionfile))
    exe "mksession! " . b:sessionfile
    echo "Session saved"
  else
    echo "Session doesn't exist"
  endif
endfunction

if !argc()
  au VimEnter * :call LoadSession()
  au VimLeave * :call SaveSession()

  map <leader>m :call StartSession()<CR>
endif
