#!/bin/bash


                           ##                   ##
                          ##                   ##
                         ##                   ##
                        ##      ###    ###   ##     ## ###    ###
                       ####   ## ##  ## ##  ####   #### ##  ## ##
                      ## ##     ##   ##    ## ##  ##       ##
                     ## ##   ####    ##   ## ##  ##       ##
                ##  ## ##  ## ##  ## ##  ## ##  ##       ## ##
               ##  ####    ####   ###   ## ##  ##        ###


#
# Here's my bashrc file! My Node, Go, and other more general configurations sit
# in here. I try to keep it as lightweight as possible, to avoid a visibly
# lengthy startup.
#

. ~/.fresh/build/shell.sh

export PATH="${HOME}/.local/bin:${PATH}"

#
# Traversing directories should be as quick and easy as possible, and bash can
# help us with this right out of the box.
#

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null

# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null

# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

#
# Keeping ones bash history can provide value feedback into habits and general
# command usage and statistics over time.
#

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Record each line as it gets issued
PROMPT_COMMAND='history -a'

# Set an overly large history value. I've haven't been bitten by this, yet!
HISTSIZE=1000000
HISTFILESIZE=1000000

# Store standard ISO-8601 timestamps with each entry
HISTTIMEFORMAT="%F %T "

export EDITOR=vim

if [[ "$TERM" =~ "screen".* ]]; then
  export PS1="\[\033[38;5;183m\]\\$\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"
else
  export PS1="[\A] \w \[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;183m\]\\$\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"
fi

alias print_colors='
  for i in {0..255}; do
    printf "\x1b[38;5;%smcolours%s\n" "${i}" "${i}"
  done | column
'

# Source local configuration if found
[[ -f ~/.bashrc.local ]] && . ~/.bashrc.local

# Go env
export GOPATH="${HOME}/go"
export GOROOT="/usr/local/go"
export PATH="${GOROOT}/bin:${PATH}"

# Ruby env
export PATH="${HOME}/.rbenv/shims:${PATH}"

# Node env
export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ]          && \. "$NVM_DIR/nvm.sh"           # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Notes
n() {
  $EDITOR ~/.notes/"$*".md
}

nls() {
  ls -c ~/.notes/ | grep "$*"
}
