#!/bin/bash

source ~/.fresh/build/shell.sh

export PS1="[\A] \w \[$(tput bold)\]\[$(tput sgr0)\]\[\033[38;5;183m\]\\$\[$(tput sgr0)\]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"

# Go env
export GOPATH=${HOME}/go
export GOROOT=/usr/local/go
export PATH=${GOROOT}/bin:${PATH}

# Node.js env
export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ]          && \. "$NVM_DIR/nvm.sh"          # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
