#!/bin/bash


                           ##                   ##
                          ##                   ##
                         ##                   ##
                        ##      ###    ###   ##     ## ###    ###
                       ####   ## ##  ## ##  ####   #### ##  ## ##
                      ## ##     ##   ##    ## ##  ##       ##
                     ## ##   ####    ##   ## ##  ##       ##
                ##  ## ##  ## ##  ## ##  ## ##  ##       ## ##
               ##  ####    ####   ###   ## ##  ##        ###


#
# Here's my bashrc file! My Node, Go, and other more general configurations sit
# in here. I try to keep it as lightweight as possible, to avoid a visibly
# lengthy startup.
#

. ~/.fresh/build/shell.sh
. ~/.git-completion.bash

export PATH="${HOME}/.local/bin:${PATH}"

#
# These colours are used in my Vim and Tmux configuration, and any other
# process that might need custom styling.
#

export COLOUR0="#002635"
export COLOUR1="#00384d"
export COLOUR2="#517F8D"
export COLOUR3="#6C8B91"
export COLOUR4="#869696"
export COLOUR5="#a1a19a"
export COLOUR6="#e6e6dc"
export COLOUR7="#fafaf8"
export COLOUR8="#ff5a67"
export COLOUR9="#f08e48"
export COLOURA="#ffcc1b"
export COLOURB="#7fc06e"
export COLOURC="#14747e"
export COLOURD="#5dd7b9"
export COLOURE="#9a70a4"
export COLOURF="#c43060"

#
# Traversing directories should be as quick and easy as possible, and bash can
# help us with this right out of the box.
#

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null

# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null

# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

#
# Keeping ones bash history can provide valuable feedback into habits and
# general command usage and statistics over time.
#

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Record each line as it gets issued
PROMPT_COMMAND="history -a"

# Set an overly large history value. I've haven't been bitten by this, yet!
HISTSIZE=1000000
HISTFILESIZE=1000000

# Store standard ISO-8601 timestamps with each entry
HISTTIMEFORMAT="%F %T "

# Hide commands prefixed with a space
HISTCONTROL=ignorespace

export EDITOR=vim

if [[ "$TERM" =~ "screen".* ]]; then
  export PS1='| '
else
  export PS1='[\A] \w | '
fi

#
# Environments setup.
#

# Brew
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# Go env
export GOPATH="${HOME}/go"
export GOROOT="/usr/local/go"
export PATH="${GOROOT}/bin:${PATH}"

# Ruby env
export GEM_HOME=~/.ruby/
export PATH="~/.ruby/bin:${PATH}"

# Node env
export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ]          && \. "$NVM_DIR/nvm.sh"           # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Rust env
export PATH="${HOME}/.cargo/bin:${PATH}"

# Source local configuration if found
[[ -f ~/.bashrc.local ]] && . ~/.bashrc.local

# Notes
n() {
  $EDITOR ~/.notes/"$*".md
}

nls() {
  ls -c ~/.notes/ | grep "$*"
}

# VimWiki
alias wiki="vim -c VimwikiIndex"

